export enum AttendanceType {
    PRESENT = 'PRESENT',
    NOT_PRESENT = 'NOT_PRESENT',
    EXCUSED_NOT_PRESENT = 'EXCUSED_NOT_PRESENT',
    UNEXCUSED_NOT_PRESENT = 'UNEXCUSED_NOT_PRESENT',
    LATE_ARRIVAL = 'LATE_PRESENT',
    EXCUSED_LATE_ARRIVAL = 'EXCUSED_LATE_PRESENT',
    UNEXCUSED_LATE_ARRIVAL = 'UNEXCUSED_LATE_PRESENT',
}