export enum AttendanceType {
  PRESENT = 'P',
  NOT_PRESENT = 'NP',
  EXCUSED_NOT_PRESENT = 'ENP',
  UNEXCUSED_NOT_PRESENT = 'UENP',
  LATE_ARRIVAL = 'LA',
  EXCUSED_LATE_ARRIVAL = 'ELA',
  UNEXCUSED_LATE_ARRIVAL = 'ULA'
}
