-- Vložení ukázkových dat do tabulky Students
INSERT INTO Students (studentId, username, name, surname) VALUES
  (1, 'student1', 'John', 'Doe'),
  (2, 'student2', 'Jane', 'Smith'),
  (3, 'student3', 'Michael', 'Johnson'),
  (4, 'student4', 'Emily', 'Davis'),
  (5, 'student5', 'Daniel', 'Martinez'),
  (6, 'student6', 'Emma', 'Garcia'),
  (7, 'student7', 'Olivia', 'Brown'),
  (8, 'student8', 'Ava', 'Miller'),
  (9, 'student9', 'Sophia', 'Wilson'),
  (10, 'student10', 'Isabella', 'Moore'),
  (11, 'student11', 'Mia', 'Taylor'),
  (12, 'student12', 'Charlotte', 'Anderson'),
  (13, 'student13', 'Amelia', 'Thomas'),
  (14, 'student14', 'Harper', 'Jackson'),
  (15, 'student15', 'Evelyn', 'White'),
  (16, 'student16', 'Abigail', 'Harris'),
  (17, 'student17', 'Ella', 'Martin'),
  (18, 'student18', 'Scarlett', 'Thompson'),
  (19, 'student19', 'Grace', 'Martinez'),
  (20, 'student20', 'Aria', 'Robinson');
