INSERT INTO Subjects (subjectId, name, abbreviation) VALUES (1, 'Praxe', 'DC'),
    (2, 'Technické dokumentace', 'TD'),
    (3, 'Multimédia a vývoj her', 'MVH'),
    (4, 'Informační a komunikační technologie', 'IT'),
    (5, 'Matematika', 'M'),
    (6, 'Aplikovaná matematika', 'AM'),
    (7, 'Databázové systémy', 'DS'),
    (8, 'Webové aplikace', 'WA'),
    (9, 'Programové vybavení', 'PV'),
    (10, 'Teoretická informatika', 'TI'),
    (11, 'Elektrotechnická měření', 'EM'),
    (12, 'Elektronika a mikroelektronika', 'EnM'),
    (13, 'Elektrotechnika', 'Ele'),
    (14, 'Základy elektrotechniky', 'ZE'),
    (15, 'Cvičení z elektrotechniky', 'CEL'),
    (16, 'Fyzika', 'F'),
    (17, 'Český jazyk a literatura', 'C'),
    (18, 'Dějepis', 'D'),
    (19, 'Cvičení z automatizace a robotiky', 'CAu'),
    (20, 'Mikroprocesorová technika', 'MT'),
    (21, 'Tělesná výchova', 'TV'),
    (22, 'Cvičení ze správy IT', 'CIT'),
    (23, 'Elektronické počítače', 'EP'),
    (24, 'Základy společenských věd', 'ZSV'),
    (25, 'Anglický jazyk', 'A'),
    (26, 'Počítačové systémy a sítě', 'PSS'),
    (27, 'Hardware', 'HW'),
    (28, 'Podnikové informační systémy', 'PIS'),
    (29, 'Automatizační technika a robotika', 'AuR'),
    (30, 'Číslicová technika', 'CT'),
    (31, 'Technický projekt', 'TP'),
    (32, 'Chemie', 'CH'),
    (33, 'Ekonomika', 'EK');
