insert into public."Subjects" ("subjectId", name, abbreviation) values (1, 'Culinary Arts', 'OC');
insert into public."Subjects" ("subjectId", name, abbreviation) values (2, 'English', 'EU');
insert into public."Subjects" ("subjectId", name, abbreviation) values (3, 'Philosophy', 'NA');
insert into public."Subjects" ("subjectId", name, abbreviation) values (5, 'Geography', 'GE');
insert into public."Subjects" ("subjectId", name, abbreviation) values (6, 'Physics', 'PHY');
insert into public."Subjects" ("subjectId", name, abbreviation) values (10, 'Philosophy', 'PHI');
insert into public."Subjects" ("subjectId", name, abbreviation) values (11, 'Music', 'MU');
insert into public."Subjects" ("subjectId", name, abbreviation) values (14, 'Film Studies', 'FS');
insert into public."Subjects" ("subjectId", name, abbreviation) values (16, 'Physical Education', 'PE');
insert into public."Subjects" ("subjectId", name, abbreviation) values (17, 'Economics', 'EC');
insert into public."Subjects" ("subjectId", name, abbreviation) values (18, 'Architecture', 'SA');
insert into public."Subjects" ("subjectId", name, abbreviation) values (22, 'Psychology', 'AF');
insert into public."Subjects" ("subjectId", name, abbreviation) values (23, 'Fashion Design', 'FD');
insert into public."Subjects" ("subjectId", name, abbreviation) values (24, 'Business', 'BUS');
insert into public."Subjects" ("subjectId", name, abbreviation) values (25, 'History', 'H');
insert into public."Subjects" ("subjectId", name, abbreviation) values (26, 'Spanish', 'SP');
insert into public."Subjects" ("subjectId", name, abbreviation) values (28, 'Business', 'B');
insert into public."Subjects" ("subjectId", name, abbreviation) values (29, 'Mathematics', 'M');
insert into public."Subjects" ("subjectId", name, abbreviation) values (30, 'Engineering', 'ENG');
